rnn_best_params:
  lr: 5.0e-05
  hidden_dim: 256
  n_layers: 3
  dropout: 0.5
  weight_decay: 5.0e-05
  underprediction_penalty: 2.0
transformer_best_params:
  lr: 5.0e-05
  d_model: 256
  nhead: 4
  num_encoder_layers: 8
  dim_feedforward: 512
  dropout: 0.6
  weight_decay: 1.0e-05
  warmup_epochs: 7
  multistep_gamma: 0.1
  underprediction_penalty: 1.5
